data:
  train_path: "data/main/datasets/train.pt"
  val_path: "data/main/datasets/val.pt"

# 31M param model
model:
  vocab_size: 2049
  num_codebooks: 4
  d_model: 384
  nhead: 6
  num_encoder_layers: 6
  num_decoder_layers: 6
  dim_feedforward: 1536
  dropout: 0.1
  activation: "relu"
  norm_first: true
  max_seq_len: 1505
  padding_idx: 2048
  scale_embeddings: true

training:
  num_epochs: 200
  batch_size: 4
  gradient_accumulation_steps: 8

  scheduled_sampling:
    start_epoch: 50
    end_epoch: 175
    start_prob: 0.0
    end_prob: 0.35
    sampling_strategy: "inverse_sigmoid" # linear, exponential
  # scheduled_sampling: null
  
  scheduler:
    type: "cosine"
    warmup_steps: 1000
    total_steps: null
    min_lr: 1.0e-6
   
  optimizer:
    type: "adamw"
    lr: 0.0003
    embedding_lr: null
    betas: [0.9, 0.98]
    eps: 1.0e-9
    weight_decay: 0.01
  
  # Logging and checkpointing
  output_dir: "models/medium"
  log_interval: 2           # Log metrics every N steps
  save_interval: 50      # Save checkpoint every N epochs
  num_workers: 8             # DataLoader workers
  
  # Resume training (optional)
  resume_from_checkpoint: "models/medium/checkpoints/checkpoint_interrupt.pt" # Path to checkpoint, or null to start fresh
