data:
  train_path: "data/main/datasets/train.pt"
  val_path: "data/main/datasets/val.pt"

# 3.9M param model
model:
  vocab_size: 2049
  num_codebooks: 4
  d_model: 128
  nhead: 2
  num_encoder_layers: 4
  num_decoder_layers: 4
  dim_feedforward: 512
  dropout: 0.0
  activation: "relu"         
  norm_first: true          
  max_seq_len: 1505
  padding_idx: 2048
  scale_embeddings: true


training:
  num_epochs: 10000
  # Effective batch size = batch_size * gradient_accumulation_steps
  batch_size: 16
  gradient_accumulation_steps: 1
  # max_grad_norm: 2.0

  scheduled_sampling:
    start_epoch: 50
    end_epoch: 175
    start_prob: 0.0
    end_prob: 0.35
    sampling_strategy: "inverse_sigmoid" # linear, exponential
  # scheduled_sampling: null
  
  # Learning rate scheduler
  scheduler:
    type: "cosine"           # Options: cosine, linear, step, plateau
    warmup_steps: 50       # Warmup for N steps
    total_steps:  null       # Total training steps (auto-calculated if omitted)
    min_lr: 1.0e-6           # Minimum learning rate
    
    # For 'step' scheduler:
    # step_size: 10          # Decay every N epochs
    # gamma: 0.5             # Multiply LR by this factor
    
    # For 'plateau' scheduler:
    # patience: 3            # Wait N epochs before reducing
    # factor: 0.5            # Multiply LR by this factor

  # Optimizer
  optimizer:
    type: "adamw"
    lr: 0.001
    embedding_lr: null # Specify for larger embedding LR
    betas: [0.9, 0.98]
    eps: 1.0e-9
    weight_decay: 0.0
  
  # Logging and checkpointing
  output_dir: "experiments/models/241025_xsmall/"
  log_interval: 2           # Log metrics every N steps
  save_interval: 50      # Save checkpoint every N epochs
  num_workers: 8             # DataLoader workers
  
  # Resume training (optional)
  resume_from_checkpoint: "experiments/models/241025_small/checkpoints/checkpoint_interrupt.pt" # Path to checkpoint, or null to start fresh
