name: demucs
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - asttokens=3.0.0
  - blas=1.0
  - brotli-python=1.0.9
  - ca-certificates=2025.1.31
  - certifi=2025.1.31
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.2.1
  - cpython=3.9.21
  - cuda-cccl=12.8.55
  - cuda-cccl_win-64=12.8.55
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.8.55
  - cuda-runtime=11.8.0
  - cuda-version=12.8
  - cycler=0.11.0
  - debugpy=1.8.12
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - filelock=3.13.1
  - fonttools=4.55.3
  - freetype=2.12.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.6.1
  - importlib_resources=6.4.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.18.1
  - jedi=0.19.2
  - jinja2=3.1.5
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.9.55
  - libcurand-dev=10.3.9.55
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.22
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.39
  - libpq=17.2
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.4.1
  - packaging=24.2
  - parso=0.8.4
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0
  - platformdirs=4.3.6
  - ply=3.11
  - prompt-toolkit=3.0.50
  - psutil=6.1.1
  - pure_eval=0.2.3
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.9.21
  - python-dateutil=2.9.0post0
  - python_abi=3.9
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pywin32=307
  - pyzmq=26.2.0
  - qt-main=5.15.2
  - requests=2.32.3
  - setuptools=75.8.0
  - sip=6.7.12
  - sqlite=3.45.3
  - stack_data=0.6.3
  - sympy=1.13.3
  - tbb=2021.8.0
  - tomli=2.0.1
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2025a
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - vc=14.42
  - vc14_runtime=14.42.34433
  - vs2015_runtime=14.42.34433
  - wcwidth=0.2.13
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - antlr4-python3-runtime==4.9.3
      - cffi==1.17.1
      - cloudpickle==3.1.1
      - demucs==4.1.0a2
      - dora-search==0.1.12
      - einops==0.8.1
      - julius==0.2.7
      - lameenc==1.8.1
      - omegaconf==2.3.0
      - openunmix==1.3.0
      - pycparser==2.22
      - pyyaml==6.0.2
      - retrying==1.3.4
      - six==1.17.0
      - soundfile==0.13.1
      - submitit==1.5.2
      - torchaudio==2.0.2
      - torchvision==0.15.2
      - tqdm==4.67.1
      - treetable==0.2.5
      - yt-dlp==2025.2.19
prefix: C:\Users\bucks\anaconda3\envs\demucs
