data:
  train_path: "data/main/7_datasets/train.pt"
  val_path: "data/main/7_datasets/val.pt"
  test_path: "data/main/7_datasets/test.pt"

model:
  vocab_size: 2049
  num_codebooks: 4
  d_model: 512
  nhead: 8         
  num_encoder_layers: 8
  num_decoder_layers: 8
  dim_feedforward: 2048
  dropout: 0.1
  activation: "relu"
  norm_first: true
  max_seq_len: 1505
  padding_idx: 2048
  scale_embeddings: true

training:
  use_pbar: false

  num_epochs: 1000
  batch_size: 32
  gradient_accumulation_steps: 1
  
  scheduler:
    type: "cosine"
    warmup_steps: 1000
    total_steps: null
    min_lr: 1.0e-7

  scheduled_sampling: null
    
  optimizer:
    type: "adamw"
    lr: 0.00005
    embedding_lr: null
    betas: [0.9, 0.98]
    eps: 1.0e-9
    weight_decay: 0.01
  
  output_dir: "models/large"
  log_interval: 20           # Log metrics every N steps
  save_interval: 200      # Save checkpoint every N epochs
  num_workers: 8             # DataLoader workers
  
  # Resume training (optional)
  resume_from_checkpoint: "models/large/checkpoints/latest.pt"